/// Mapa de códigos de moneda a información legible (Bandera + Nombre)
/// Basado en los códigos soportados por Frankfurter API y comunes.
const Map<String, ({String flag, String name})> kCurrencyDetails = {
  'ARS': (flag: '🇦🇷', name: 'Peso Argentino'),
  'AUD': (flag: '🇦🇺', name: 'Dólar Australiano'),
  'BGN': (flag: '🇧🇬', name: 'Lev Búlgaro'),
  'BOB': (flag: '🇧🇴', name: 'Boliviano'),
  'BRL': (flag: '🇧🇷', name: 'Real Brasileño'),
  'CAD': (flag: '🇨🇦', name: 'Dólar Canadiense'),
  'CHF': (flag: '🇨🇭', name: 'Franco Suizo'),
  'CLP': (flag: '🇨🇱', name: 'Peso Chileno'),
  'CNY': (flag: '🇨🇳', name: 'Yuan Chino'),
  'COP': (flag: '🇨🇴', name: 'Peso Colombiano'),
  'CRC': (flag: '🇨🇷', name: 'Colón Costarricense'),
  'CZK': (flag: '🇨🇿', name: 'Corona Checa'),
  'DKK': (flag: '🇩🇰', name: 'Corona Danesa'),
  'DOP': (flag: '🇩🇴', name: 'Peso Dominicano'),
  'EUR': (flag: '🇪🇺', name: 'Euro'),
  'GBP': (flag: '🇬🇧', name: 'Libra Esterlina'),
  'GTQ': (flag: '🇬🇹', name: 'Quetzal'),
  'HKD': (flag: '🇭🇰', name: 'Dólar de Hong Kong'),
  'HNL': (flag: '🇭🇳', name: 'Lempira'),
  'HUF': (flag: '🇭🇺', name: 'Forinto Húngaro'),
  'IDR': (flag: '🇮🇩', name: 'Rupia Indonesia'),
  'ILS': (flag: '🇮🇱', name: 'Nuevo Shekel Israelí'),
  'INR': (flag: '🇮🇳', name: 'Rupia India'),
  'ISK': (flag: '🇮🇸', name: 'Corona Islandesa'),
  'JPY': (flag: '🇯🇵', name: 'Yen Japonés'),
  'KRW': (flag: '🇰🇷', name: 'Won Surcoreano'),
  'MXN': (flag: '🇲🇽', name: 'Peso Mexicano'),
  'MYR': (flag: '🇲🇾', name: 'Ringgit Malayo'),
  'NIO': (flag: '🇳🇮', name: 'Córdoba'),
  'NOK': (flag: '🇳🇴', name: 'Corona Noruega'),
  'NZD': (flag: '🇳🇿', name: 'Dólar Neozelandés'),
  'PAB': (flag: '🇵🇦', name: 'Balboa'),
  'PEN': (flag: '🇵🇪', name: 'Sol Peruano'),
  'PHP': (flag: '🇵🇭', name: 'Peso Filipino'),
  'PLN': (flag: '🇵🇱', name: 'Zloty Polaco'),
  'PYG': (flag: '🇵🇾', name: 'Guaraní'),
  'RON': (flag: '🇷🇴', name: 'Leu Rumano'),
  'SEK': (flag: '🇸🇪', name: 'Corona Sueca'),
  'SGD': (flag: '🇸🇬', name: 'Dólar de Singapur'),
  'THB': (flag: '🇹🇭', name: 'Baht Tailandés'),
  'TRY': (flag: '🇹🇷', name: 'Lira Turca'),
  'USD': (flag: '🇺🇸', name: 'Dólar Estadounidense'),
  'UYU': (flag: '🇺🇾', name: 'Peso Uruguayo'),
  'VES': (flag: '🇻🇪', name: 'Bolívar'),
  'ZAR': (flag: '🇿🇦', name: 'Rand Sudafricano'),
};
